---
title: Sushi Bar Application
author:
 - Miłosz Białczak <br/> 218295
 - Radosław Kobak <br/> 218288
 - Martna Łagożna <br/> 218218
 - Jan Pedryc <br/> 191090
 - Wojciech Rosiński <br/> 200101
 - Szymon Wojciechowski <br/> 218154
papersize: A4
fontsize: 12pt
documentclass: report
...
